### ISSUE TITLE
Allow users to specify alternative dataLayer names

### ISSUE THREAD

**Issue by philpott** [Mikeulrich75/dataLayerBuilderEnhancedEcommerce#1]
Please allow users to specify alternative data layer names.

**Comment by Mikeulrich75** [comment]
Are you asking me to build in functionality to rename the dataLayer to an alternative if the client has a custom dataLayer setup in their GTM container? Or are you asking me to create a custom field in the ecommerce action parameter (add, remove, detail, checkout, etc...) that allows the user to create a custom dataLayer parameter action? 

Sorry, just want a little clarity before I make my updates. :)

Thanks!

**Comment by philpott** [comment]
Just the ability to specify a different data layer name so if they customized it on there page.

That way if the container has decided to change the name your script will grab/create the correct queue from the window.

**Comment by Mikeulrich75** [comment]
Phil,

Do you have a recommended method, API, example code for doing this? 

The queryPermission API I used requires that I manually set the permissions (read/write/execute) for any global variables in the permissions section of the template, which is what I did for the dataLayer and have to do for any new custom dataLayer's I queue. 

Renaming the dataLayer in the script is easy, but dynamically updating the new dataLayer in the templates permissions and granting access automatically/dynamically appears impossible.  This looks like it can only be done manually by the user in the template permissions. 

I added a text box in the custom template that allows me to rename the dataLayer if the user has a custom dataLayer (**Screenshot 1**), but the user will have to manually update the new custom dataLayer global variables permission (**Screenshot 2**) if they want it to push data to their new dataLayer. 

Is this what you had in mind, or do you have a better method for achieving this, any suggestions an examples would be super helpful! 

**Screenshot 1:**
![Screen Shot 2019-10-24 at 3 21 53 PM](https://user-images.githubusercontent.com/53228114/67522533-8899db80-f672-11e9-8ae4-d25462a060d2.png)

**Screenshot 2:**
![Screen Shot 2019-10-24 at 3 22 18 PM](https://user-images.githubusercontent.com/53228114/67522616-a9fac780-f672-11e9-953a-e84f320d522b.png)


Thanks in advance!

**Comment by philpott** [comment]
Yes that was what we where thinking and you are correct, you wouldn't be able to update the permissions to match that dynamically -- unfortunately we missed that one sorry. You might want to make a note in the description that this will only work if the dataLayer name has not been changed. 

FYI I've also added a request for a dataLayer.push call to our API wishlist.

**Comment by Mikeulrich75** [comment]
Thanks for the feedback, I was hoping there was something super cool I was missing that would allow me to create this functionality. 

I will leave the template as is, and as you have requested add a note to the descriptions stating that this will only work on a standard **dataLayer** and not one that has had the name changed. 

PS: A dataLayer.push API will be awesome, while you're at it put in a request for support for the RegEx object. :p 

Thanks again!

**Comment by Mikeulrich75** [comment]
I have made an update to the README.md file as requested. This template should be good for you to do your final review on. :)

Thanks!
